### ISSUE TITLE
ECC Output is incorrect

### ISSUE THREAD

**Issue by zzrrxx** [calvinmetcalf/pem2jwk#1]
Today when I try to convert an EC private key to JWK, the output is as follows:
{ kty: 'EC',
  crv: 'p256',
 x:'80,254,94,161,225,123,235,71,80,194,173,131,7,185,97,166,27,249,140,161,177,240,29,216,126,35,243,149,194,3,233,107',  y:'58,225,193,227,233,152,103,68,171,125,216,222,73,3,181,64,1,13,77,91,169,91,179,113,25,161,180,186,97,229,241,82',
  ext: true,
d:'217,112,50,213,26,20,135,143,245,133,124,189,132,40,217,15,31,74,27,215,3,29,46,64,227,70,47,20,142,209,179,17' }
The value of parameters 'x','y' should be Base64Url-encoded.
And after I debug the source code, I found the code "var str = buf.toArray().toString('base64');" doesn't work as expected. Maybe "var str = new Buffer(buf.toArray(), 'binary').toString('base64');" can be used to encoded the binary correctly.

**Comment by calvinmetcalf** [comment]
just pushed up a fix, take a look and if it looks good I'll publish

**Comment by zzrrxx** [comment]
It looks good to me. Thanks.

**Comment by UselezzProgrammer** [comment]
Close the issue.

**Comment by omsmith** [comment]
Hey @calvinmetcalf. Care to publish a new version here?

**Comment by calvinmetcalf** [comment]
done

**Comment by omsmith** [comment]
Thanks
